### ISSUE TITLE
bitbucket 8.16

### ISSUE THREAD

**Issue by simont26** [beigi-reza/atlassian-software#7]
agent doesnt generate valid key for 8.16

**Comment by marrowsh** [comment]
not even for 8.9

**Comment by marrowsh** [comment]
> not even for 8.9

sorry. I had to change java version for bitbucket to 1.8 in /opt/java and now it works for me on version 8.9

**Comment by simont26** [comment]
brilliant Marrowsh, does it matter which docker image is used?

**Comment by marrowsh** [comment]
> brilliant Marrowsh, does it matter which docker image is used?

hey @simont26.
I tried the official one from Atlassian on docker hub.
now I used 8.17 version and it still works. but with a warning for java 1.8 deprecation.

**Comment by simont26** [comment]
@marrowsh how did you go about updating the java?  

I added using docker run -it --name java8 -v /opt/java8 openjdk:8

this is my docker file

```
#
#   __   _ __  __            __       __    ____     _____                     
#  / /  (_) /_/ /  __ ______/ /_____ / /_  / __/__  / _/ /__    _____ ________ 
# / _ \/ / __/ _ \/ // / __/  '_/ -_) __/ _\ \/ _ \/ _/ __/ |/|/ / _ `/ __/ -_)
#/_.__/_/\__/_.__/\_,_/\__/_/\_\\__/\__/ /___/\___/_/ \__/|__,__/\_,_/_/  \__/ 
#                                                                              
#   Docker Compose for Run bitbucket
#   Test for bitbucket Server 7.x
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=150.50.50.0/24 my-net

version: '3.4'
services:
  bitbucket:
    image: 'atlassian/bitbucket-server:8.17'  # Use the custom image you built   
    container_name: bitbucket
    hostname: bitbucket
    restart: always
    environment:
      JAVA_HOME: /opt/java8
      BITBUCKET_HOME: /var/atlassian/application-data/bitbucket/
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: 'jdbc:postgresql://db:5432/bitbucket'
      JDBC_USER: bitbucket
      JDBC_PASSWORD: 'X&/LmRJDsw3wJf<30j39'
      SERVER_SCHEME: 'https'
      SERVER_SECURE: 'true'
      SERVER_PROXY_PORT: '443'
      SERVER_PROXY_NAME: 'bitbucket.simontodd.me'
      JVM_MINIMUM_MEMORY: 2048m
      JVM_MAXIMUM_MEMORY: 6000m

    volumes:
      - bitbucket-Data:/var/atlassian/application-data/bitbucket
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
      - java8:/opt/java8
    networks:
      my-net:
       aliases:
        - bit
    ports:
      - 7990:7990
      - 7999:7999
  db:
    image: postgres:15
    container_name: bitbucket-database
    hostname: bitbucket-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'X&/LmRJDsw3wJf<30j39'
      POSTGRES_USER: bitbucket
      POSTGRES_DB: bitbucket
    volumes:
      - bitbucketDbVolume:/var/lib/postgresql/data
    networks:
      my-net:
       aliases:
        - bit-db        
        
volumes:
 bitbucket-Data:
   name: bitbucket-Data
 bitbucketDbVolume:
   name: bitbucketDbVolume

networks:
  my-net:
    external: true

```

When its setting up i keep getting the same error 

![image](https://github.com/beigi-reza/atlassian-software/assets/14054952/dfe382d0-f8e4-4310-ba13-053e3aca228f)

any help is greatly appreciated!

**Comment by marrowsh** [comment]
> @marrowsh how did you go about updating the java?
> 
> I added using docker run -it --name java8 -v /opt/java8 openjdk:8
> 
> this is my docker file
> 
> ```
> #
> #   __   _ __  __            __       __    ____     _____                     
> #  / /  (_) /_/ /  __ ______/ /_____ / /_  / __/__  / _/ /__    _____ ________ 
> # / _ \/ / __/ _ \/ // / __/  '_/ -_) __/ _\ \/ _ \/ _/ __/ |/|/ / _ `/ __/ -_)
> #/_.__/_/\__/_.__/\_,_/\__/_/\_\\__/\__/ /___/\___/_/ \__/|__,__/\_,_/_/  \__/ 
> #                                                                              
> #   Docker Compose for Run bitbucket
> #   Test for bitbucket Server 7.x
> #   Need  "my-net" Network for Run this File
> #   docker network create --driver bridge --subnet=150.50.50.0/24 my-net
> 
> version: '3.4'
> services:
>   bitbucket:
>     image: 'atlassian/bitbucket-server:8.17'  # Use the custom image you built   
>     container_name: bitbucket
>     hostname: bitbucket
>     restart: always
>     environment:
>       JAVA_HOME: /opt/java8
>       BITBUCKET_HOME: /var/atlassian/application-data/bitbucket/
>       JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
>       JDBC_DRIVER: org.postgresql.Driver
>       JDBC_URL: 'jdbc:postgresql://db:5432/bitbucket'
>       JDBC_USER: bitbucket
>       JDBC_PASSWORD: 'XXX'
>       SERVER_SCHEME: 'https'
>       SERVER_SECURE: 'true'
>       SERVER_PROXY_PORT: '443'
>       SERVER_PROXY_NAME: 'XXX'
>       JVM_MINIMUM_MEMORY: 2048m
>       JVM_MAXIMUM_MEMORY: 6000m
> 
>     volumes:
>       - bitbucket-Data:/var/atlassian/application-data/bitbucket
>       - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
>       - java8:/opt/java8
>     networks:
>       my-net:
>        aliases:
>         - bit
>     ports:
>       - 7990:7990
>       - 7999:7999
>   db:
>     image: postgres:15
>     container_name: bitbucket-database
>     hostname: bitbucket-database
>     restart: always
>     ports:
>       - "5432:5432"
>     environment:
>       POSTGRES_PASSWORD: 'X&/LmRJDsw3wJf<30j39'
>       POSTGRES_USER: bitbucket
>       POSTGRES_DB: bitbucket
>     volumes:
>       - bitbucketDbVolume:/var/lib/postgresql/data
>     networks:
>       my-net:
>        aliases:
>         - bit-db        
>         
> volumes:
>  bitbucket-Data:
>    name: bitbucket-Data
>  bitbucketDbVolume:
>    name: bitbucketDbVolume
> 
> networks:
>   my-net:
>     external: true
> ```
> 
> When its setting up i keep getting the same error
> 
> ![image](https://private-user-images.githubusercontent.com/14054952/297132392-dfe382d0-f8e4-4310-ba13-053e3aca228f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM1OTcsIm5iZiI6MTcwNTUxMzI5NywicGF0aCI6Ii8xNDA1NDk1Mi8yOTcxMzIzOTItZGZlMzgyZDAtZjhlNC00MzEwLWJhMTMtMDUzZTNhY2EyMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTMzMzY0ZTJkYWI2YzA2ZjMyOGQ4MDRhZTJmZDhkM2FlOWM0NWM3YzExMjllMGM4OTMzMWM3ZDcwODRhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVhihO-rdBxHS8GPim9M-swSm7p2r5V1Pp-7CCR0618)
> 
> any help is greatly appreciated!

This is the part in my compose file that I made changes:
you won't need to define JAVA_HOME 
just download  the tar file of openjdk 1.8 and extract in on root of the cloned repo. then change its name to **java** and :
# cd java
# mkdir openjdk =>the reason for making such a dir is because when you run the docker image you find this path>/opt/java/openjdk
# mv * openjdk 
now run the compose file for bitbucket.
```
version: '3.4'
services:
  bitbucket:
    image: "atlassian/bitbucket-server:8.17"
    container_name: bitbucket
    hostname: bitbucket
    restart: always
    environment:
      BITBUCKET_HOME: /var/atlassian/application-data/bitbucket/
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: 'jdbc:postgresql://db:5432/bitbucket'
      JDBC_USER: bitbucket
      JDBC_PASSWORD: 'X&/LmRJDsw3wJ'
      #SERVER_SCHEME: 'https'
      #SERVER_SECURE: 'true'
      #SERVER_PROXY_PORT: '443'
      #SERVER_PROXY_NAME: 'bitbucket.mysite.com'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - bitbucket-Data:/var/atlassian/application-data/bitbucket
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
      **- ./java:/opt/java**
    networks:
      my-net:
       aliases:
        - bit
    ports:
      - 7990:7990
      - 7999:7999
     ```
